### ISSUE TITLE
The character metadata endpoint errors out when getting metadata for multiple characters.

### ISSUE THREAD

**Issue by willemm** [eosfrontier/orthanc#25] opened 2021-03-02 22:39 UTC
https://github.com/eosfrontier/orthanc/blob/8c5ae2b67abc58a68dc7b673464b09544fabbdc3/v2/character/meta/index.php#L6

This line checks the 'id' parameter, which is an optional parameter.  If it's not given, it returns a PHP warning that garbles the json output.

**Comment by WafflesMcDuff** [comment] 2021-03-03 02:27
I have removed the line that is a duplicate of #26

**Closed** 2021-03-03 03:23 UTC
Labels: Prio 0: Quick Win, bug
